<div align="justify"><b>Betrifft: Auskunft gem. DSGVO - Art. 15, 30</b><br>
    <br>Sehr geehrte Damen! Sehr geehrte Herren!
    <br>
    <br>Ihre Organisation verarbeitet als Verantwortliche im Sinne des Art&nbsp;4.&nbsp;Z&nbsp;7&nbsp;DSGVO personenbezogene Daten%CHAPTER_9_10_TEXT%, ich ersuche daher:

    <ol style="{ white-space:nowrap; }">
        <li>gem Art. 15 Abs.1 DSGVO um die Übermittlung der Daten selbst aus den mir bekannten Verarbeitungen:
            <br>
            <ul style="list-style-type: disc;">
                %APPLICATION_LIST%
            </ul>
            <br>
        </li>
        <li><div style="{ white-space:nowrap;  page-break-inside: avoid; }">Gem. Art.&nbsp;15&nbsp;Abs.&nbsp;1&nbsp;DSGVO um die Übermittlung des für den Betroffenen zugönglichen Teils des Verarbeitungsverzeichnisses gem. Art.&nbsp;30&nbsp;DSGVO bzw. einer Auflistung inklusive der folgenden Angaben in allgemeinverständlicher Form
                <br>
                <ul style="list-style-type: disc;">
                    <li>die Verarbeitungszwecke und Rechtsgrundlage(n)</li>
                    <li>die Kategorien verarbeiteter Daten</li>
                    <li>die Empfänger(-kategorien) inkl. etwaiger internationaler Empfänger</li>
                    <li>die Speicherdauer - falls diese <i>nicht</i> feststeht, die Kriterien für deren Festlegung</li>
                    <li>die Herkunft oder Entstehung der Daten</li>
                </ul>
                <br>
                <br>für alle oben genannten und auch für evtl. mir nicht bekannte Verarbeitungen, bei denen Ihre Organisation Verantwortlicher gem. Art.&nbsp;4&nbsp;Abs.&nbsp;7&nbsp;DSGVO ist. Gleichzeitig erstreckt sich mein Auskunftsersuchen auch auf diese Verarbeitungen, sollten sie in offenkundigem Zusammenhang mit den oben genannten stehen oder diese abgel&ouml;st haben.
	    </div>
            <div style="{ white-space:nowrap; page-break-inside: avoid; }"><i>Hinweis:</i> Ein Verweis auf Rechtsgrundlage(n) ersetzt nicht die Angabe der Speicherdauer in allgemein verständlicher Form, wenn diese feststeht.  In diesem Fall w&auml;re die konkrete Dauer in eines Zeitraums (etwa in Jahren) zu nennen, f&uuml;r den die Daten tats&auml;chlich &uuml;blicherweise gespeichert werden.</div>
        </li>
        <li><nobr>
		<div style="{ white-space:nowrap;  page-break-inside: avoid; }">Die Beauskunftung der ggf. anonymisierten oder pseudonymisierten Protokolldaten (siehe DSK-Entscheidung
                    <i>K121.632/0008-DSK/2010</i>: Protokolldaten sind sog. &quot;äussere Verfahrensdaten&quot; und ebenfalls zu beauskunften) aus denen zumindest die abfragende Organisationseinheit oder ein sonstiges organisatorisches Eingrenzungskennzeichen und der Zeitpunkt der Abfrage hervorgeht.
                </div>
            </nobr>
        </li>
    </ol>
    <div style="{ white-space:nowrap; page-break-inside: avoid; }">Zu Zwecken der einfacheren Auffindung der auch mich bezogenen Datensätze gebe ich folgende Daten an:<br>
	<br><b>%ID_DATASET%</b>
    </div>
    <div style="{ white-space:nowrap; page-break-inside: avoid; }">Zu Zwecken der Glaubhaftmachung als rechtmäßiger Antragssteller schließe ich folgende Nachweise an:<br>
        <br><b>%ID_DOCUMENTS%</b>
        </b><br><br>
	<i>Hinweis:</i> Der Identitätsnachweis, wie im alten §50e&nbsp;Abs.&nbsp;1&nbsp;DSG&nbsp;2000 verpflichtend gefordert, ist nunmehr gem. Art.&nbsp;12&nbsp;DSGVO sowie §&nbsp;42&nbsp;Abs.&nbsp;7&nbsp;DSG&nbsp;(neu) eine optionale Bestimmung, wenn begründete Zweifel an der Identität des Antragsstellers bestehen, also die Gefahr bestünde, dass eine dritte, unberechtigte Person das Auskunftsersuchen gestellt haben könnte.  Die von mir erbrachten Nachweise sollten einen solchen Zweifel jedenfalls ausräumen, zusätzlich besteht die Möglichkeit einer Zustellung &quot;zu eigenen Handen&quot; - hierbei überprüft die Post die Identität anhand eines amtlichen Lichtbildausweises.  Aus den genannten Gründen wird die Anforderung weiterer Nachweise als unverhältnismäßig zu bewerten sein. 
    </div>

    <div style="{ white-space:nowrap; page-break-inside: avoid; }">Mit freundlichen Gr&uuml;ßen
        <br>
        <br>
        <br>
        <br>%REQUESTOR_NAME%
        <br>
        <br>
        <br>
        <br>
    </div>
</div>