<div align="justify"><b>Betrifft: Auskunft gem. DSGVO - Art. 15, 30</b><br>
    <br>Sehr geehrte Damen! Sehr geehrte Herren!
    <br>
    <br>Ihre Behörde verarbeitet als Verantwortliche im Sinne des Art&nbsp;4.&nbsp;Z&nbsp;7&nbsp;DSGVO personenbezogene Daten%CHAPTER_9_10_TEXT%, ich ersuche daher:

    <ol style="{ white-space:nowrap; }">
        <li>gem Art. 15 Abs.1 DSGVO um die Übermittlung der Daten selbst aus den mir bekannten Verarbeitungen:
            <br>
            <ul style="list-style-type: disc;">
                %APPLICATION_LIST%
            </ul>
            <br>
        </li>
        <li><div style="{ white-space:nowrap;  page-break-inside: avoid; }">Gem. Art.&nbsp;15&nbsp;Abs.&nbsp;1&nbsp;DSGVO um die Übermittlung des für den Betroffenen zugönglichen Teils des Verarbeitungsverzeichnisses gem. Art.&nbsp;30&nbsp;DSGVO bzw. einer Auflistung inklusive der folgenden Angaben in allgemeinverständlicher Form
                <br>
                <ul style="list-style-type: disc;">
                    <li>die Verarbeitungszwecke und Rechtsgrundlage(n)</li>
                    <li>die Kategorien verarbeiteter Daten</li>
                    <li>die Empfänger(-kategorien) inkl. etwaiger internationaler Empfänger</li>
                    <li>die Speicherdauer - falls diese <i>nicht</i> feststeht, die Kriterien für deren Festlegung</li>
                    <li>die Herkunft oder Entstehung der Daten</li>
                </ul>
                <br>
                <br>für alle oben genannten und auch für evtl. mir nicht bekannte Verarbeitungen, bei denen Ihre Behörde Verantwortlicher gem. Art.&nbsp;4&nbsp;Abs.&nbsp;7&nbsp;DSGVO ist. Gleichzeitig erstreckt sich mein Auskunftsersuchen auch auf diese Verarbeitungen, sollten sie in offenkundigem Zusammenhang mit den oben genannten stehen oder diese abgel&ouml;st haben.
	    </div>
            <div style="{ white-space:nowrap; page-break-inside: avoid; }"><i>Hinweis:</i> Ein Verweis auf Rechtsgrundlage(n) ersetzt nicht die Angabe der Speicherdauer in allgemein verständlicher Form, wenn diese feststeht.  In diesem Fall w&auml;re die konkrete Dauer in eines Zeitraums (etwa in Jahren) zu nennen, f&uuml;r den die Daten tats&auml;chlich &uuml;blicherweise gespeichert werden.</div>
        </li>
        <li><nobr>
		<div style="{ white-space:nowrap;  page-break-inside: avoid; }">Die Beauskunftung der ggf. anonymisierten oder pseudonymisierten Protokolldaten (siehe DSK-Entscheidung
                    <i>K121.632/0008-DSK/2010</i>: Protokolldaten sind sog. &quot;äussere Verfahrensdaten&quot; und ebenfalls zu beauskunften) aus denen zumindest die abfragende Dienststelle oder ein sonstiges organisatorisches Eingrenzungskennzeichen und der Zeitpunkt der Abfrage hervorgeht.
                </div>
            </nobr>
        </li>
    </ol>
    <div style="{ white-space:nowrap; page-break-inside: avoid; }">Zu Zwecken der einfacheren Auffindung der auch mich bezogenen Datensätze gebe ich folgende Daten an:<br>
	<br><b>%ID_DATASET%</b>
    </div>
    <div style="{ white-space:nowrap; page-break-inside: avoid; }">Zu Nachweis meiner Identität als rechtmäßiger Antragssteller ist dieses PDF-Dokument elektronisch signiert.  
<br>Eine Überprüfung der Signatur ist unter <a href="https://www.signaturpruefung.gv.at/">https://www.signaturpruefung.gv.at/</a> möglich.<br>
<br>
<i>Hinweis:</i> Eine qualifizierte elektronische Signatur ist gem. Art.&nbsp;25&nbsp;Abs.&nbsp;2&nbsp;eIDAS-VO sowie §4&nbsp;Abs.&nbsp;1&nbsp;SVG der eigenh&auml;ndigen Unterschrift gleichgestellt, ausserdem gilt sie im Verkehr mit Beh&ouml;rden gem. §&nbsp;4&nbsp;Abs.&nbsp;1,2&nbsp;E-GovG als eindeutiger Identit&auml;tsnachweis.  Ich ersuche aus diesem Grund von der Anforderung weiterer Nachweise, wie etwa Ausweiskopien, abzusehen.<br>

<br>
	Ich ersuche mir die Auskunft entweder per RSa-Brief gem. §21&nbsp;ZustellG &quot;zu eigenen Handen&quot; oder falls möglich mittels elektronischem Zustelldienst gem. §§28ff&nbsp;ZustellG zukommen zu lassen und weise ausdrücklich darauf hin, dass ich <b>keine</b> Beauskunftung per unverschlüsselter Email-Nachricht wünsche.<br><br>

<i>Hinweis:</i> Eine unverschlüsselte Zusendung per Email kann eine Verletzung des §&nbsp;54&nbsp;DSG bzw. Art.&nbsp;32&nbsp;Abs.&nbsp;1&nbsp;lit&nbsp;a&nbsp;DSGVO darstellen.
    </div>

    <div style="{ white-space:nowrap; page-break-inside: avoid; }">Mit freundlichen Gr&uuml;ßen
        <br>
        <br>
        <br>
        <br>%REQUESTOR_NAME%
        <br>(elektronisch signiert)
        <br>
        <br>
        <br>
    </div>
</div>